// Render a RepoContext into a proposed AGENTS.md — the payoff: the signals,
// turned into imperative house rules an agent can follow. Pure.

import { redact } from '../redact.js';
import { deriveRules } from '../rules.js';

/**
 * @param {import('../distill.js').RepoContext} ctx
 * @param {{rules?: {id:string,text:string}[]}} [opts]  optional pre-phrased rules (LLM layer)
 * @returns {string}
 */
export function renderAgents(ctx, opts = {}) {
  const L = [];
  L.push('# AGENTS.md — proposed by Grain');
  L.push('');
  L.push(
    `_Distilled from ${ctx.sessionCount} session(s) of real agent work in this repo. ` +
      'These are observations to review, not gospel — keep what fits, cut what does not._',
  );
  L.push('');

  // Commands
  const top = (cat) => ctx.commands?.[cat]?.[0]?.cmd;
  const test = top('test');
  const build = top('build');
  const run = top('run');
  if (test || build || run) {
    L.push('## Commands');
    if (test) L.push(`- **Test:** \`${redact(test)}\``);
    if (build) L.push(`- **Build:** \`${redact(build)}\``);
    if (run) L.push(`- **Run:** \`${redact(run)}\``);
    L.push('');
  }

  // Conventions -> imperative rules (deterministic, optionally LLM-rephrased)
  const rules = opts.rules || deriveRules(ctx);
  if (rules.length) {
    L.push('## Conventions');
    for (const r of rules) L.push(`- ${redact(r.text)}`);
    L.push('');
  }

  // Preferences (recurring corrections)
  const rec = ctx.corrections?.recurring || [];
  if (rec.length) {
    L.push('## Preferences (things reviewers repeated)');
    for (const r of rec.slice(0, 8)) L.push(`- ${redact(r.sample)}  _(said ${r.n}×)_`);
    L.push('');
  }

  // Anti-patterns (abandoned paths)
  const files = (ctx.reverts?.files || []).filter((f) => !f.file.startsWith('('));
  if (files.length) {
    L.push('## Watch out (paths tried and backed out)');
    for (const f of files.slice(0, 6)) L.push(`- \`${redact(f.file)}\` was reverted ${f.n}×`);
    L.push('');
  }

  L.push('---');
  L.push('_Generated by Grain from captured agent sessions. Edit freely; re-run to refresh._');
  return L.join('\n').trimEnd() + '\n';
}
